import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log("🌱 Seeding full education data...")

  // Clear existing data
  await prisma.grammarPoint.deleteMany()
  await prisma.photo.deleteMany()
  await prisma.album.deleteMany()
  await prisma.vocabulary.deleteMany()
  await prisma.lesson.deleteMany()
  await prisma.course.deleteMany()
  await prisma.category.deleteMany()
  await prisma.heroSlide.deleteMany()
  await prisma.hSKLevel.deleteMany()
  await prisma.feature.deleteMany()
  await prisma.ctaStat.deleteMany()
  await prisma.review.deleteMany()

  // ============= Categories =============
  const basic = await prisma.category.create({
    data: {
      name: "Tiếng Trung Cơ Bản",
      slug: "tieng-trung-co-ban",
      description: "Các khóa học tiếng Trung dành cho người mới bắt đầu, từ cơ bản đến trung cấp. Phù hợp cho học viên chưa có nền tảng hoặc muốn củng cố kiến thức nền.",
    },
  })

  const advanced = await prisma.category.create({
    data: {
      name: "Tiếng Trung Nâng Cao",
      slug: "tieng-trung-nang-cao",
      description: "Các khóa học tiếng Trung nâng cao, chuyên sâu cho học viên đã có nền tảng vững. Tập trung vào kỹ năng giao tiếp chuyên nghiệp và HSK cấp cao.",
    },
  })

  const specialized = await prisma.category.create({
    data: {
      name: "Tiếng Trung Chuyên Ngành",
      slug: "tieng-trung-chuyen-nganh",
      description: "Các khóa học tiếng Trung chuyên ngành như kinh doanh, du lịch, dịch thuật. Phù hợp cho người đi làm và học viên có nhu cầu chuyên sâu.",
    },
  })

  // ============= Courses =============
  // Create HSK 1-6 main courses
  const hskCourses = await prisma.course.createMany({
    data: [
      {
        title: "HSK 1 – Tiếng Trung cho người mới bắt đầu",
        slug: "hsk-1",
        description: "Khóa học HSK 1 dành cho người mới bắt đầu. Làm quen với tiếng Trung từ con số 0, học cách chào hỏi và giao tiếp cơ bản.",
        level: "HSK 1",
        badgeText: "Mới bắt đầu",
        badgeColor: "bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-200",
        vocabularyCount: 150,
        grammarCount: 45,
        lessonCount: 25,
        durationHours: 40,
        categoryId: basic.id,
      },
      {
        title: "HSK 2 – Giao tiếp tiếng Trung cơ bản",
        slug: "hsk-2",
        description: "Giao tiếp cơ bản trong cuộc sống hàng ngày. Nâng cao kỹ năng giao tiếp, mở rộng từ vựng và mẫu câu thông dụng.",
        level: "HSK 2",
        badgeText: "Sơ cấp",
        badgeColor: "bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-200",
        vocabularyCount: 300,
        grammarCount: 60,
        lessonCount: 20,
        lectures: 20,
        durationHours: 60,
        categoryId: basic.id,
      },
      {
        title: "HSK 3 – Tiếng Trung trung cấp",
        slug: "hsk-3",
        description: "Bước vào giao tiếp nâng cao. Giao tiếp và viết thành thạo hơn trong các tình huống thường gặp.",
        level: "HSK 3",
        badgeText: "Trung cấp",
        badgeColor: "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-200",
        vocabularyCount: 600,
        grammarCount: 80,
        lessonCount: 25,
        lectures: 25,
        durationHours: 80,
        categoryId: basic.id,
      },
      {
        title: "HSK 4 – Sẵn sàng du học và làm việc",
        slug: "hsk-4",
        description: "Sẵn sàng cho môi trường du học và làm việc. Giao tiếp tự tin trong các tình huống phức tạp.",
        level: "HSK 4",
        badgeText: "Du học/Làm việc",
        badgeColor: "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-200",
        vocabularyCount: 1200,
        grammarCount: 120,
        lessonCount: 30,
        lectures: 30,
        durationHours: 100,
        categoryId: advanced.id,
      },
      {
        title: "HSK 5 – Tiếng Trung cao cấp",
        slug: "hsk-5",
        description: "Thành thạo giao tiếp chuyên sâu. Đọc báo, xem phim, giao tiếp trong môi trường chuyên nghiệp.",
        level: "HSK 5",
        badgeText: "Cao cấp",
        badgeColor: "bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-200",
        vocabularyCount: 2500,
        grammarCount: 150,
        lessonCount: 35,
        lectures: 35,
        durationHours: 120,
        categoryId: advanced.id,
      },
      {
        title: "HSK 6 – Trình độ chuyên gia",
        slug: "hsk-6",
        description: "Đạt trình độ gần như người bản ngữ. Hiểu và sử dụng tiếng Trung trong mọi tình huống phức tạp.",
        level: "HSK 6",
        badgeText: "Chuyên gia",
        badgeColor: "bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-200",
        vocabularyCount: 5000,
        grammarCount: 200,
        lessonCount: 40,
        lectures: 40,
        durationHours: 150,
        categoryId: advanced.id,
      },
    ],
  })

  // Get HSK 1 course for lessons
  const hsk1 = await prisma.course.findUnique({
    where: { slug: "hsk-1" },
  })

  // Course section courses
  await prisma.course.createMany({
    data: [
      {
        title: "Nhập Môn Tiếng Trung Căn Bản Tốc",
        slug: "nhap-mon-tieng-trung",
        image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&h=450&fit=crop&q=80",
        instructor: "Cô Bảo Anh",
        instructorAvatar: "https://i.pravatar.cc/150?img=5",
        price: "499,000₫",
        students: "30 học viên",
        rating: "3 sao",
        level: "beginner",
        tag: "Bán chạy",
        lectures: 20,
        durationHours: 35,
        categoryId: basic.id,
      },
      {
        title: "Luyện Giải Đề HSK 4 & 5 HSKK",
        slug: "luyen-giai-de-hsk-4-5",
        image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=450&fit=crop&q=80",
        instructor: "Fredy Pham",
        instructorAvatar: "https://i.pravatar.cc/150?img=12",
        price: "1,299,000₫",
        originalPrice: "1,999,000₫",
        students: "35 học viên",
        rating: "5 sao",
        level: "intermediate",
        tag: "Phổ biến HSK 4",
        lectures: 42,
        durationHours: 65,
        categoryId: advanced.id,
      },
      {
        title: "Tiếng Trung Kinh Doanh",
        slug: "tieng-trung-kinh-doanh",
        image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=450&fit=crop&q=80",
        instructor: "Cô Ngọc",
        instructorAvatar: "https://i.pravatar.cc/150?img=9",
        price: "699,000₫",
        students: "30 học viên",
        rating: "29 sao",
        level: "advanced",
        lectures: 28,
        durationHours: 50,
        categoryId: specialized.id,
      },
      {
        title: "Tiếng Trung qua Phim Ảnh",
        slug: "tieng-trung-qua-phim-anh",
        image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&h=450&fit=crop&q=80",
        instructor: "Mai Linh",
        instructorAvatar: "https://i.pravatar.cc/150?img=20",
        price: "599,000₫",
        students: "30 học viên",
        rating: "3 sao",
        level: "beginner",
        tag: "Mới nhất",
        lectures: 24,
        durationHours: 40,
        categoryId: basic.id,
      },
      {
        title: "Biện Pháp Dịch Trung - Việt",
        slug: "bien-phap-dich-trung-viet",
        image: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&h=450&fit=crop&q=80",
        instructor: "Kiều Phạm",
        instructorAvatar: "https://i.pravatar.cc/150?img=32",
        price: "2,499,000₫",
        students: "35 học viên",
        rating: "5 sao",
        level: "advanced",
        lectures: 36,
        durationHours: 72,
        categoryId: specialized.id,
      },
      {
        title: "Ngữ pháp HSK 1 Từng Nội dung",
        slug: "ngu-phap-hsk-1",
        image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=450&fit=crop&q=80",
        instructor: "Cô Thi",
        instructorAvatar: "https://i.pravatar.cc/150?img=44",
        price: "699,000₫",
        students: "35 học viên",
        rating: "5 sao",
        level: "beginner",
        tag: "Phổ biến HSK 1",
        lectures: 18,
        durationHours: 30,
        categoryId: basic.id,
      },
    ]
  })

  // ============= Lessons =============
  const lessons = await prisma.lesson.createMany({
    data: [
      {
        title: "Giới thiệu làm quen Tiếng Trung",
        titleChinese: "",
        description: "Các nét và quy tắc viết trong tiếng Trung",
        order: 1,
        courseId: hsk1!.id,
        isLocked: false,
        progress: 75,
      },
      {
        title: "Xin chào",
        titleChinese: "",
        description: "Cách nói xin chào với từ 你好, Cách đếm số từ 1-99",
        order: 2,
        courseId: hsk1!.id,
        isLocked: false,
        progress: 75,
      },
      {
        title: "Tiếng Trung không khó lắm",
        titleChinese: "",
        description: "Từ vựng về các thành viên trong gia đình, Cấu trúc câu 不太 + ADJ, Cách hỏi và trả lời với từ 吗？",
        order: 3,
        courseId: hsk1!.id,
        isLocked: false,
        progress: 60,
      },
      {
        title: "Hẹn ngày mai gặp lại",
        titleChinese: "",
        description: "Từ vựng về các ngôn ngữ, Hỏi đáp đi đâu làm gì",
        order: 4,
        courseId: hsk1!.id,
        isLocked: false,
        progress: 0,
      },
      {
        title: "Học nghe nói bài 1, 2, 3",
        titleChinese: "",
        description: "Nắm được cách phân biệt của các vận mẫu và thanh mẫu bài 1,2,3",
        order: 5,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Bạn đi đâu?",
        titleChinese: "你去哪儿？",
        description: "Hỏi đáp đi đâu với chữ 哪儿, Hỏi đáp về thứ trong tuần với từ 几, Cách nói lời tạm biệt, xin lỗi",
        order: 6,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Đây là thầy Vương",
        titleChinese: "这是王老师",
        description: "Hỏi đáp về công việc, sức khỏe, Cách nói lời cảm ơn",
        order: 7,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Tôi học tiếng Trung",
        titleChinese: "我学汉语",
        description: "Hỏi đáp về họ tên, quốc gia, Hỏi đáp với từ 什么",
        order: 8,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Học nghe nói bài 4, 5, 6",
        titleChinese: "",
        description: "Nắm được cách phân biệt của các vận mẫu và thanh mẫu bài 4,5",
        order: 9,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "KIỂM TRA LẦN 1",
        titleChinese: "",
        description: "Kiểm tra tổng hợp kiến thức các bài đã học",
        order: 10,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Bạn ăn gì?",
        titleChinese: "你吃什么？",
        description: "Từ vựng về các món ăn, Hỏi đáp về ăn uống, Từ vựng về các buổi trong ngày",
        order: 11,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Một cân táo bao nhiêu tiền?",
        titleChinese: "一斤苹果多少钱？",
        description: "Từ vựng về hoa quả, Cách hỏi về số lượng với từ 多少 và 几, Cách hỏi về số tiền với từ 多少钱",
        order: 12,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Tôi đổi nhân dân tệ",
        titleChinese: "我换人民币",
        description: "Từ vựng về loại tiền tệ, Cách nói số tiền từ hàng chục tới hàng vạn",
        order: 13,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Học nghe nói bài 7, 8, 9",
        titleChinese: "",
        description: "Luyện phản xạ nghe các bài 7, 8, 9",
        order: 14,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Bạn sống ở đâu?",
        titleChinese: "你住在哪儿？",
        description: "Hỏi đáp về nơi sống với từ 住, Cách hỏi đáp về số điện thoại",
        order: 15,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Chúng tôi đều là du học sinh",
        titleChinese: "我们都是留学生",
        description: "Cách giới thiệu về bản thân, Cách dùng của chữ 都 và 也",
        order: 16,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Bạn học ở đâu?",
        titleChinese: "你在哪儿学习？",
        description: "Từ vựng về các kỹ năng trong tiếng Trung, Cách dùng của từ 怎么样、但是",
        order: 17,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Học nghe nói bài 10, 11, 12",
        titleChinese: "",
        description: "Luyện phản xạ nghe các bài 10, 11, 12",
        order: 18,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "KIỂM TRA LẦN 2",
        titleChinese: "",
        description: "Kiểm tra tổng hợp kiến thức các bài đã học",
        order: 19,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Đây có phải là thuốc bắc không?",
        titleChinese: "这是中药吗？",
        description: "Từ vựng về các đồ vật cơ bản, Làm quen với lượng từ",
        order: 20,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Xe của bạn là cái mới hay là cái cũ?",
        titleChinese: "你的车是新的还是旧的？",
        description: "Từ vựng về các loại xe và động từ đi kèm, Cách dùng của 有一点儿、还是",
        order: 21,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Công ty của bạn có bao nhiêu nhân viên?",
        titleChinese: "你的公司有多少员工？",
        description: "Từ vựng về nghề nghiệp, Cách dùng từ 只、大概, Cách nói về sự ước lượng",
        order: 22,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Học nghe nói bài 13, 14, 15",
        titleChinese: "",
        description: "Luyện phản xạ nghe các bài 13, 14, 15",
        order: 23,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "KIỂM TRA LẦN 3",
        titleChinese: "",
        description: "Kiểm tra tổng hợp kiến thức các bài đã học",
        order: 24,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "ÔN TẬP",
        titleChinese: "",
        description: "Ôn tập tổng hợp toàn bộ khóa học",
        order: 25,
        courseId: hsk1!.id,
        isLocked: true,
        progress: 0,
      },
    ],
  })

  // Get HSK 2-6 courses for lessons
  const hsk2 = await prisma.course.findUnique({ where: { slug: "hsk-2" } })
  const hsk3 = await prisma.course.findUnique({ where: { slug: "hsk-3" } })
  const hsk4 = await prisma.course.findUnique({ where: { slug: "hsk-4" } })
  const hsk5 = await prisma.course.findUnique({ where: { slug: "hsk-5" } })
  const hsk6 = await prisma.course.findUnique({ where: { slug: "hsk-6" } })

  // ============= HSK 2 Lessons =============
  await prisma.lesson.createMany({
    data: [
      {
        title: "Ôn tập HSK 1",
        titleChinese: "复习 HSK 1",
        description: "Ôn tập lại kiến thức HSK 1, củng cố từ vựng và ngữ pháp cơ bản",
        order: 1,
        courseId: hsk2!.id,
        isLocked: false,
        progress: 0,
      },
      {
        title: "Bây giờ mấy giờ rồi?",
        titleChinese: "现在几点了？",
        description: "Học cách hỏi và trả lời về thời gian, Từ vựng về giờ phút",
        order: 2,
        courseId: hsk2!.id,
        isLocked: false,
        progress: 0,
      },
      {
        title: "Hôm nay thứ mấy?",
        titleChinese: "今天星期几？",
        description: "Từ vựng về ngày trong tuần, tháng trong năm, Cách nói ngày tháng năm",
        order: 3,
        courseId: hsk2!.id,
        isLocked: false,
        progress: 0,
      },
      {
        title: "Thời tiết hôm nay thế nào?",
        titleChinese: "今天天气怎么样？",
        description: "Từ vựng về thời tiết, Cách mô tả thời tiết và khí hậu",
        order: 4,
        courseId: hsk2!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Tôi muốn uống cà phê",
        titleChinese: "我想喝咖啡",
        description: "Cấu trúc 想 + động từ, Từ vựng về đồ uống và món ăn",
        order: 5,
        courseId: hsk2!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Đi mua sắm",
        titleChinese: "去购物",
        description: "Từ vựng về mua sắm, Cách hỏi giá và mặc cả",
        order: 6,
        courseId: hsk2!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Gia đình tôi có 4 người",
        titleChinese: "我家有四口人",
        description: "Từ vựng về thành viên gia đình, Cấu trúc câu với 有",
        order: 7,
        courseId: hsk2!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Sở thích của tôi",
        titleChinese: "我的爱好",
        description: "Từ vựng về sở thích, hoạt động giải trí, Cách nói về sở thích cá nhân",
        order: 8,
        courseId: hsk2!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Học nghe nói bài 1-4",
        titleChinese: "",
        description: "Luyện nghe và phát âm các bài từ 1 đến 4",
        order: 9,
        courseId: hsk2!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "KIỂM TRA GIỮA KHÓA",
        titleChinese: "",
        description: "Kiểm tra tổng hợp kiến thức nửa đầu khóa học",
        order: 10,
        courseId: hsk2!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Đi bệnh viện",
        titleChinese: "去医院",
        description: "Từ vựng về sức khỏe và bệnh viện, Cách mô tả triệu chứng bệnh",
        order: 11,
        courseId: hsk2!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Phương tiện giao thông",
        titleChinese: "交通工具",
        description: "Từ vựng về các loại xe và phương tiện, Cách hỏi đường và chỉ đường",
        order: 12,
        courseId: hsk2!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Đi du lịch",
        titleChinese: "去旅游",
        description: "Từ vựng về du lịch, khách sạn, địa điểm tham quan",
        order: 13,
        courseId: hsk2!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Học ở thư viện",
        titleChinese: "在图书馆学习",
        description: "Từ vựng về học tập, thư viện, trường học",
        order: 14,
        courseId: hsk2!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Cuối tuần làm gì?",
        titleChinese: "周末做什么？",
        description: "Từ vựng về hoạt động cuối tuần, giải trí",
        order: 15,
        courseId: hsk2!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Học nghe nói bài 5-8",
        titleChinese: "",
        description: "Luyện nghe và phát âm các bài từ 5 đến 8",
        order: 16,
        courseId: hsk2!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "KIỂM TRA CUỐI KHÓA",
        titleChinese: "",
        description: "Kiểm tra tổng hợp toàn bộ khóa học HSK 2",
        order: 17,
        courseId: hsk2!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "ÔN TẬP TỔNG HỢP",
        titleChinese: "",
        description: "Ôn tập và củng cố toàn bộ kiến thức HSK 2",
        order: 18,
        courseId: hsk2!.id,
        isLocked: true,
        progress: 0,
      },
    ],
  })

  // ============= HSK 3 Lessons =============
  await prisma.lesson.createMany({
    data: [
      {
        title: "Ôn tập HSK 2",
        titleChinese: "复习 HSK 2",
        description: "Ôn tập lại kiến thức HSK 2, củng cố từ vựng và ngữ pháp",
        order: 1,
        courseId: hsk3!.id,
        isLocked: false,
        progress: 0,
      },
      {
        title: "Giới thiệu về bản thân",
        titleChinese: "自我介绍",
        description: "Cách giới thiệu chi tiết về bản thân, gia đình, học vấn",
        order: 2,
        courseId: hsk3!.id,
        isLocked: false,
        progress: 0,
      },
      {
        title: "Tìm việc làm",
        titleChinese: "找工作",
        description: "Từ vựng về công việc, phỏng vấn, CV",
        order: 3,
        courseId: hsk3!.id,
        isLocked: false,
        progress: 0,
      },
      {
        title: "Thuê nhà",
        titleChinese: "租房子",
        description: "Từ vựng về nhà ở, đồ đạc, tiện nghi",
        order: 4,
        courseId: hsk3!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Đi ngân hàng",
        titleChinese: "去银行",
        description: "Từ vựng về ngân hàng, tiền bạc, giao dịch",
        order: 5,
        courseId: hsk3!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Gửi bưu kiện",
        titleChinese: "寄包裹",
        description: "Từ vựng về bưu điện, gửi hàng, dịch vụ chuyển phát",
        order: 6,
        courseId: hsk3!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Đặt vé máy bay",
        titleChinese: "订机票",
        description: "Từ vựng về sân bay, máy bay, đặt vé",
        order: 7,
        courseId: hsk3!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Nhà hàng Trung Hoa",
        titleChinese: "中餐厅",
        description: "Từ vựng về món ăn Trung Hoa, cách gọi món",
        order: 8,
        courseId: hsk3!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Tập thể dục",
        titleChinese: "锻炼身体",
        description: "Từ vựng về thể thao, sức khỏe, tập luyện",
        order: 9,
        courseId: hsk3!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Học nghe nói bài 1-5",
        titleChinese: "",
        description: "Luyện nghe và phát âm các bài từ 1 đến 5",
        order: 10,
        courseId: hsk3!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "KIỂM TRA GIỮA KHÓA",
        titleChinese: "",
        description: "Kiểm tra tổng hợp kiến thức nửa đầu khóa học",
        order: 11,
        courseId: hsk3!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Mời bạn đến nhà chơi",
        titleChinese: "请你来家里玩",
        description: "Từ vựng về lời mời, đón tiếp khách, giao tiếp xã hội",
        order: 12,
        courseId: hsk3!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Mua quần áo",
        titleChinese: "买衣服",
        description: "Từ vựng về quần áo, phụ kiện, màu sắc, kích cỡ",
        order: 13,
        courseId: hsk3!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Đi xem phim",
        titleChinese: "去看电影",
        description: "Từ vựng về rạp chiếu phim, thể loại phim, diễn viên",
        order: 14,
        courseId: hsk3!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Học tiếng Trung",
        titleChinese: "学习汉语",
        description: "Từ vựng về học tập, phương pháp học, khó khăn khi học",
        order: 15,
        courseId: hsk3!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Văn hóa Trung Quốc",
        titleChinese: "中国文化",
        description: "Từ vựng về văn hóa, truyền thống, lễ hội Trung Quốc",
        order: 16,
        courseId: hsk3!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Học nghe nói bài 6-10",
        titleChinese: "",
        description: "Luyện nghe và phát âm các bài từ 6 đến 10",
        order: 17,
        courseId: hsk3!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "KIỂM TRA CUỐI KHÓA",
        titleChinese: "",
        description: "Kiểm tra tổng hợp toàn bộ khóa học HSK 3",
        order: 18,
        courseId: hsk3!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "ÔN TẬP TỔNG HỢP",
        titleChinese: "",
        description: "Ôn tập và củng cố toàn bộ kiến thức HSK 3",
        order: 19,
        courseId: hsk3!.id,
        isLocked: true,
        progress: 0,
      },
    ],
  })

  // ============= HSK 4 Lessons =============
  await prisma.lesson.createMany({
    data: [
      {
        title: "Ôn tập HSK 3",
        titleChinese: "复习 HSK 3",
        description: "Ôn tập lại kiến thức HSK 3, củng cố từ vựng và ngữ pháp",
        order: 1,
        courseId: hsk4!.id,
        isLocked: false,
        progress: 0,
      },
      {
        title: "Trò chuyện về cuộc sống",
        titleChinese: "聊生活",
        description: "Từ vựng và mẫu câu về cuộc sống hàng ngày, thói quen sinh hoạt",
        order: 2,
        courseId: hsk4!.id,
        isLocked: false,
        progress: 0,
      },
      {
        title: "Môi trường làm việc",
        titleChinese: "工作环境",
        description: "Từ vựng về văn phòng, đồng nghiệp, văn hóa công ty",
        order: 3,
        courseId: hsk4!.id,
        isLocked: false,
        progress: 0,
      },
      {
        title: "Kế hoạch tương lai",
        titleChinese: "未来计划",
        description: "Cách nói về kế hoạch, ước mơ, mục tiêu tương lai",
        order: 4,
        courseId: hsk4!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Đi du học",
        titleChinese: "去留学",
        description: "Từ vựng về du học, thủ tục, cuộc sống du học sinh",
        order: 5,
        courseId: hsk4!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Trải nghiệm văn hóa",
        titleChinese: "文化体验",
        description: "Từ vựng về văn hóa, sự khác biệt văn hóa, thích nghi",
        order: 6,
        courseId: hsk4!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Công nghệ và Internet",
        titleChinese: "科技和网络",
        description: "Từ vựng về công nghệ, Internet, mạng xã hội",
        order: 7,
        courseId: hsk4!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Bảo vệ môi trường",
        titleChinese: "保护环境",
        description: "Từ vựng về môi trường, ô nhiễm, bảo vệ thiên nhiên",
        order: 8,
        courseId: hsk4!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Giáo dục và học tập",
        titleChinese: "教育和学习",
        description: "Từ vựng về hệ thống giáo dục, phương pháp học tập",
        order: 9,
        courseId: hsk4!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Học nghe nói bài 1-5",
        titleChinese: "",
        description: "Luyện nghe và phát âm các bài từ 1 đến 5",
        order: 10,
        courseId: hsk4!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "KIỂM TRA GIỮA KHÓA 1",
        titleChinese: "",
        description: "Kiểm tra tổng hợp kiến thức phần 1",
        order: 11,
        courseId: hsk4!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Sức khỏe và y tế",
        titleChinese: "健康和医疗",
        description: "Từ vựng về sức khỏe, bệnh tật, điều trị",
        order: 12,
        courseId: hsk4!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Giao tiếp kinh doanh",
        titleChinese: "商务交流",
        description: "Từ vựng về kinh doanh, đàm phán, hợp tác",
        order: 13,
        courseId: hsk4!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Du lịch và khám phá",
        titleChinese: "旅游和探索",
        description: "Từ vựng về du lịch, danh lam thắng cảnh, trải nghiệm",
        order: 14,
        courseId: hsk4!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Ẩm thực Á Đông",
        titleChinese: "亚洲美食",
        description: "Từ vựng về ẩm thực, nguyên liệu, cách chế biến",
        order: 15,
        courseId: hsk4!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Thể thao và giải trí",
        titleChinese: "体育和娱乐",
        description: "Từ vựng về các môn thể thao, giải trí, sở thích",
        order: 16,
        courseId: hsk4!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Học nghe nói bài 6-10",
        titleChinese: "",
        description: "Luyện nghe và phát âm các bài từ 6 đến 10",
        order: 17,
        courseId: hsk4!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "KIỂM TRA GIỮA KHÓA 2",
        titleChinese: "",
        description: "Kiểm tra tổng hợp kiến thức phần 2",
        order: 18,
        courseId: hsk4!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "KIỂM TRA CUỐI KHÓA",
        titleChinese: "",
        description: "Kiểm tra tổng hợp toàn bộ khóa học HSK 4",
        order: 19,
        courseId: hsk4!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "ÔN TẬP TỔNG HỢP",
        titleChinese: "",
        description: "Ôn tập và củng cố toàn bộ kiến thức HSK 4",
        order: 20,
        courseId: hsk4!.id,
        isLocked: true,
        progress: 0,
      },
    ],
  })

  // ============= HSK 5 Lessons =============
  await prisma.lesson.createMany({
    data: [
      {
        title: "Ôn tập HSK 4",
        titleChinese: "复习 HSK 4",
        description: "Ôn tập lại kiến thức HSK 4, củng cố từ vựng và ngữ pháp nâng cao",
        order: 1,
        courseId: hsk5!.id,
        isLocked: false,
        progress: 0,
      },
      {
        title: "Văn học và nghệ thuật",
        titleChinese: "文学和艺术",
        description: "Từ vựng về văn học, nghệ thuật, các tác phẩm nổi tiếng",
        order: 2,
        courseId: hsk5!.id,
        isLocked: false,
        progress: 0,
      },
      {
        title: "Chính trị và xã hội",
        titleChinese: "政治和社会",
        description: "Từ vựng về chính trị, xã hội, các vấn đề thời sự",
        order: 3,
        courseId: hsk5!.id,
        isLocked: false,
        progress: 0,
      },
      {
        title: "Kinh tế và tài chính",
        titleChinese: "经济和金融",
        description: "Từ vựng về kinh tế, tài chính, đầu tư, thương mại",
        order: 4,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Khoa học và công nghệ",
        titleChinese: "科学和技术",
        description: "Từ vựng về khoa học, công nghệ, phát minh, đổi mới",
        order: 5,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Lịch sử Trung Quốc",
        titleChinese: "中国历史",
        description: "Từ vựng về lịch sử, triều đại, sự kiện lịch sử quan trọng",
        order: 6,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Triết học và tư tưởng",
        titleChinese: "哲学和思想",
        description: "Từ vựng về triết học, tư tưởng, các học thuyết",
        order: 7,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Pháp luật và quyền lợi",
        titleChinese: "法律和权利",
        description: "Từ vựng về pháp luật, quyền lợi, nghĩa vụ công dân",
        order: 8,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Tôn giáo và tín ngưỡng",
        titleChinese: "宗教和信仰",
        description: "Từ vựng về tôn giáo, tín ngưỡng, phong tục tập quán",
        order: 9,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Đọc báo và tạp chí",
        titleChinese: "读报纸和杂志",
        description: "Luyện đọc hiểu báo chí, bài báo chuyên sâu",
        order: 10,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "KIỂM TRA GIỮA KHÓA 1",
        titleChinese: "",
        description: "Kiểm tra tổng hợp kiến thức phần 1",
        order: 11,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Y học cổ truyền",
        titleChinese: "传统医学",
        description: "Từ vựng về y học cổ truyền, thuốc Đông y, châm cứu",
        order: 12,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Kiến trúc và xây dựng",
        titleChinese: "建筑和建设",
        description: "Từ vựng về kiến trúc, xây dựng, công trình",
        order: 13,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Nông nghiệp và nông thôn",
        titleChinese: "农业和农村",
        description: "Từ vựng về nông nghiệp, nông thôn, canh tác",
        order: 14,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Công nghiệp và sản xuất",
        titleChinese: "工业和生产",
        description: "Từ vựng về công nghiệp, sản xuất, chế tạo",
        order: 15,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Biến đổi khí hậu",
        titleChinese: "气候变化",
        description: "Từ vựng về biến đổi khí hậu, ảnh hưởng, giải pháp",
        order: 16,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Toàn cầu hóa",
        titleChinese: "全球化",
        description: "Từ vựng về toàn cầu hóa, hội nhập quốc tế",
        order: 17,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Đọc hiểu nâng cao",
        titleChinese: "高级阅读",
        description: "Luyện đọc hiểu các văn bản phức tạp, chuyên sâu",
        order: 18,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "KIỂM TRA GIỮA KHÓA 2",
        titleChinese: "",
        description: "Kiểm tra tổng hợp kiến thức phần 2",
        order: 19,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "KIỂM TRA CUỐI KHÓA",
        titleChinese: "",
        description: "Kiểm tra tổng hợp toàn bộ khóa học HSK 5",
        order: 20,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "ÔN TẬP TỔNG HỢP",
        titleChinese: "",
        description: "Ôn tập và củng cố toàn bộ kiến thức HSK 5",
        order: 21,
        courseId: hsk5!.id,
        isLocked: true,
        progress: 0,
      },
    ],
  })

  // ============= HSK 6 Lessons =============
  await prisma.lesson.createMany({
    data: [
      {
        title: "Ôn tập HSK 5",
        titleChinese: "复习 HSK 5",
        description: "Ôn tập lại kiến thức HSK 5, củng cố từ vựng và ngữ pháp chuyên sâu",
        order: 1,
        courseId: hsk6!.id,
        isLocked: false,
        progress: 0,
      },
      {
        title: "Văn học cổ điển",
        titleChinese: "古典文学",
        description: "Nghiên cứu văn học cổ điển Trung Quốc, thơ, phú, từ, tùy bút",
        order: 2,
        courseId: hsk6!.id,
        isLocked: false,
        progress: 0,
      },
      {
        title: "Thành ngữ và tục ngữ",
        titleChinese: "成语和俗语",
        description: "Học các thành ngữ, tục ngữ, điển cố trong tiếng Trung",
        order: 3,
        courseId: hsk6!.id,
        isLocked: false,
        progress: 0,
      },
      {
        title: "Nghệ thuật tu từ",
        titleChinese: "修辞艺术",
        description: "Nghiên cứu các biện pháp tu từ, cách viết văn hay",
        order: 4,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Phân tích văn bản",
        titleChinese: "文本分析",
        description: "Phân tích chuyên sâu các văn bản văn học, báo chí",
        order: 5,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Tranh luận và biện luận",
        titleChinese: "辩论和论证",
        description: "Kỹ năng tranh luận, lập luận, bảo vệ quan điểm",
        order: 6,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Viết luận văn",
        titleChinese: "写论文",
        description: "Kỹ năng viết luận văn, bài nghiên cứu chuyên môn",
        order: 7,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Dịch thuật chuyên nghiệp",
        titleChinese: "专业翻译",
        description: "Kỹ thuật dịch thuật, dịch văn bản chuyên ngành",
        order: 8,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Giao tiếp học thuật",
        titleChinese: "学术交流",
        description: "Giao tiếp trong môi trường học thuật, hội thảo, nghiên cứu",
        order: 9,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Triết học Đông phương",
        titleChinese: "东方哲学",
        description: "Nghiên cứu sâu về triết học Đông phương, Nho, Phật, Đạo",
        order: 10,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "KIỂM TRA GIỮA KHÓA 1",
        titleChinese: "",
        description: "Kiểm tra tổng hợp kiến thức phần 1",
        order: 11,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Lịch sử tư tưởng",
        titleChinese: "思想史",
        description: "Nghiên cứu lịch sử tư tưởng, các trường phái học thuật",
        order: 12,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Phân tích xã hội",
        titleChinese: "社会分析",
        description: "Phân tích các hiện tượng xã hội, vấn đề đương đại",
        order: 13,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Kinh tế chính trị",
        titleChinese: "政治经济",
        description: "Nghiên cứu về kinh tế chính trị, chính sách công",
        order: 14,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Quan hệ quốc tế",
        titleChinese: "国际关系",
        description: "Từ vựng và kiến thức về quan hệ quốc tế, ngoại giao",
        order: 15,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Phê bình văn học",
        titleChinese: "文学批评",
        description: "Kỹ năng phê bình, đánh giá tác phẩm văn học",
        order: 16,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Nghiên cứu văn hóa",
        titleChinese: "文化研究",
        description: "Nghiên cứu chuyên sâu về văn hóa Trung Quốc",
        order: 17,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Báo chí và truyền thông",
        titleChinese: "新闻和传媒",
        description: "Nghiên cứu về báo chí, truyền thông đại chúng",
        order: 18,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Đọc hiểu chuyên gia",
        titleChinese: "专家阅读",
        description: "Đọc hiểu các văn bản học thuật, chuyên môn cao",
        order: 19,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "KIỂM TRA GIỮA KHÓA 2",
        titleChinese: "",
        description: "Kiểm tra tổng hợp kiến thức phần 2",
        order: 20,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "Luyện thi HSK 6",
        titleChinese: "HSK 6 考试准备",
        description: "Luyện đề thi, chiến lược làm bài thi HSK 6",
        order: 21,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "KIỂM TRA CUỐI KHÓA",
        titleChinese: "",
        description: "Kiểm tra tổng hợp toàn bộ khóa học HSK 6",
        order: 22,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
      {
        title: "ÔN TẬP TỔNG HỢP",
        titleChinese: "",
        description: "Ôn tập và củng cố toàn bộ kiến thức HSK 6",
        order: 23,
        courseId: hsk6!.id,
        isLocked: true,
        progress: 0,
      },
    ],
  })

  const lesson1 = await prisma.lesson.findFirst({
    where: { courseId: hsk1!.id, order: 1 },
  })
  const lesson2 = await prisma.lesson.findFirst({
    where: { courseId: hsk1!.id, order: 2 },
  })

  // ============= Vocabulary =============
  await prisma.vocabulary.createMany({
    data: [
      {
        word: "你好",
        pinyin: "nǐ hǎo",
        meaning: "Xin chào",
        lessonId: lesson1!.id,
      },
      {
        word: "再见",
        pinyin: "zài jiàn",
        meaning: "Tạm biệt",
        lessonId: lesson1!.id,
      },
      {
        word: "我",
        pinyin: "wǒ",
        meaning: "Tôi",
        lessonId: lesson1!.id,
      },
      {
        word: "你",
        pinyin: "nǐ",
        meaning: "Bạn",
        lessonId: lesson1!.id,
      },
      {
        word: "他",
        pinyin: "tā",
        meaning: "Anh ấy",
        lessonId: lesson1!.id,
      },
      {
        word: "谢谢",
        pinyin: "xiè xiè",
        meaning: "Cảm ơn",
        lessonId: lesson2!.id,
      },
      {
        word: "对不起",
        pinyin: "duì bù qǐ",
        meaning: "Xin lỗi",
        lessonId: lesson2!.id,
      },
      {
        word: "没关系",
        pinyin: "méi guān xì",
        meaning: "Không sao",
        lessonId: lesson2!.id,
      },
    ],
  })

  // ============= Grammar Points =============
  await prisma.grammarPoint.createMany({
    data: [
      {
        title: 'Câu "Shi" (是)',
        titleChinese: "是",
        description: "Cấu trúc câu cơ bản sử dụng 是 (là) để nhận dạng và định nghĩa.",
        order: 1,
        courseId: hsk1!.id,
      },
      {
        title: 'Câu hỏi với "Ma" (吗)',
        titleChinese: "吗",
        description: "Tạo câu hỏi yes/no bằng cách thêm 吗 vào cuối câu khẳng định.",
        order: 2,
        courseId: hsk1!.id,
      },
      {
        title: 'Diễn đạt sở hữu với "De" (的)',
        titleChinese: "的",
        description: "Sử dụng 的 để thể hiện sở hữu và mối quan hệ giữa các danh từ.",
        order: 3,
        courseId: hsk1!.id,
      },
      {
        title: 'Phủ định với "Bu" (不)',
        titleChinese: "不",
        description: "Phủ định động từ và tính từ sử dụng 不 (không).",
        order: 4,
        courseId: hsk1!.id,
      },
      {
        title: 'Số đếm và Lượng từ',
        titleChinese: "量词",
        description: "Học cách đếm và sử dụng lượng từ phù hợp với danh từ.",
        order: 5,
        courseId: hsk1!.id,
      },
    ],
  })

  // ============= Hero Slides =============
  await prisma.heroSlide.createMany({
    data: [
      {
        image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1920&h=800&fit=crop",
        badge: "Khóa học mới 2024",
        badgeColor: "bg-yellow-500 text-black",
        title: "Chinh phục HSK 1 - HSK 6",
        description: "Hệ thống bài giảng video chất lượng cao. Tích hợp AI luyện phát âm và học từ để thi phòng phù hợp nhất Việt Nam.",
        primaryCtaText: "Xem lộ trình",
        primaryCtaHref: "#courses",
        secondaryCtaText: "Thử học miễn phí",
        secondaryCtaHref: "/courses",
        overlayGradient: "from-black/80 via-black/40 to-transparent",
        order: 1,
      },
      {
        image: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=1920&h=800&fit=crop",
        badge: "Tài liệu chất lượng",
        badgeColor: "bg-white text-red-600",
        title: "Tài liệu học tập đầy đủ",
        description: "Kho tài liệu phong phú với hàng ngàn bài tập, từ vựng và mẹo học tập hiệu quả.",
        primaryCtaText: "Khám phá ngay",
        primaryCtaHref: "/vocabulary",
        overlayGradient: "from-red-900/90 via-red-800/50 to-transparent",
        order: 2,
      },
      {
        image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1920&h=800&fit=crop",
        badge: "Cộng đồng học tập",
        badgeColor: "bg-blue-500 text-white",
        title: "Học cùng cộng đồng",
        description: "Tham gia cộng đồng học viên năng động, chia sẻ kinh nghiệm và cùng tiến bộ.",
        primaryCtaText: "Tham gia ngay",
        primaryCtaHref: "/contact",
        overlayGradient: "from-blue-900/90 via-blue-800/50 to-transparent",
        order: 3,
      },
    ]
  })

  // ============= HSK Levels =============
  await prisma.hSKLevel.createMany({
    data: [
      {
        level: 1,
        title: "HSK 1",
        badge: "~3 tháng",
        badgeColor: "bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-200",
        description: "Nhìn vào cô ấy chẳng mệt gì đâu. Làm mệt với tâm trí thôi mà sao hết như làm máy.",
        vocabularyCount: "150 từ",
        targetAudience: "Mới bắt đầu",
        targetIcon: "group",
        accentColor: "border-orange-200 bg-orange-50 text-orange-600 dark:bg-surface-dark dark:border-orange-900 dark:text-orange-400",
        bgGradient: "bg-gradient-to-br from-orange-400 to-yellow-300",
        href: "/courses/hsk-1",
        order: 1,
      },
      {
        level: 2,
        title: "HSK 2",
        badge: "~3-4 tháng",
        badgeColor: "bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-200",
        description: "Giao tiếp cơ bản trong ngày thường. Nội dung của mỗi sư đại như bài học giúp bạn nắm.",
        vocabularyCount: "300 từ",
        targetAudience: "Sơ cấp",
        targetIcon: "trending_up",
        accentColor: "border-orange-200 bg-orange-50 text-orange-600 dark:bg-surface-dark dark:border-orange-900 dark:text-orange-400",
        bgGradient: "bg-gradient-to-br from-orange-400 to-yellow-300",
        href: "/courses/hsk-2",
        order: 2,
      },
      {
        level: 3,
        title: "HSK 3",
        badge: "~4-5 tháng",
        badgeColor: "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-200",
        description: "Bước vào giao tiếp cấp. Giao tiếp và viết thành thạo hơn bình thường sao cho học với tâm.",
        vocabularyCount: "600 từ",
        targetAudience: "Trung cấp",
        targetIcon: "school",
        accentColor: "border-red-200 bg-red-50 text-red-600 dark:bg-surface-dark dark:border-red-900 dark:text-red-400",
        bgGradient: "bg-gradient-to-br from-red-400 to-orange-400",
        href: "/courses/hsk-3",
        order: 3,
      },
      {
        level: 4,
        title: "HSK 4",
        badge: "~5-6 tháng",
        badgeColor: "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-200",
        description: "Sẵn sàng cho môi trường du học. Du sĩ tại máy và đại các chúng sẽ trong tình sẽ cấp.",
        vocabularyCount: "1200 từ",
        targetAudience: "Du học/Làm việc",
        targetIcon: "work",
        accentColor: "border-red-200 bg-red-50 text-red-600 dark:bg-surface-dark dark:border-red-900 dark:text-red-400",
        bgGradient: "bg-gradient-to-br from-red-500 to-red-400",
        href: "/courses/hsk-4",
        order: 4,
      },
      {
        level: 5,
        title: "HSK 5",
        badge: "~6-8 tháng",
        badgeColor: "bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-200",
        description: "Thành thạo vào ngôn đối tài. Đọc báo, xem phim, giao tiếp một ngành dĩnh đại sĩ.",
        vocabularyCount: "2500 từ",
        targetAudience: "Cao cấp",
        targetIcon: "stars",
        accentColor: "border-indigo-200 bg-indigo-50 text-indigo-600 dark:bg-surface-dark dark:border-indigo-900 dark:text-indigo-400",
        bgGradient: "bg-gradient-to-br from-purple-500 to-indigo-500",
        href: "/courses/hsk-5",
        order: 5,
      },
      {
        level: 6,
        title: "HSK 6",
        badge: "~8-12 tháng",
        badgeColor: "bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-200",
        description: "Đạt chân các ngữ giá cao. Hiểu cấu kể đến văn đại thị hải nghị một ngành kính loại.",
        vocabularyCount: "5000+ từ",
        targetAudience: "Chuyên gia",
        targetIcon: "psychology",
        accentColor: "border-blue-200 bg-blue-50 text-blue-600 dark:bg-surface-dark dark:border-blue-900 dark:text-blue-400",
        bgGradient: "bg-gradient-to-br from-indigo-600 to-blue-600",
        href: "/courses/hsk-6",
        order: 6,
      },
    ]
  })

  // ============= Features (Why Choose Us) =============
  await prisma.feature.createMany({
    data: [
      {
        icon: "📚",
        iconBg: "bg-blue-100 dark:bg-blue-900/30",
        iconColor: "text-blue-600 dark:text-blue-400",
        title: "HSK 1-6 Hoàn chỉnh",
        description: "Chương trình học từ cơ bản đến nâng cao",
        order: 1,
      },
      {
        icon: "👥",
        iconBg: "bg-green-100 dark:bg-green-900/30",
        iconColor: "text-green-600 dark:text-green-400",
        title: "Lớp học nhỏ",
        description: "Tối đa 4-6 học viên để đảm bảo chất lượng",
        order: 2,
      },
      {
        icon: "🏅",
        iconBg: "bg-purple-100 dark:bg-purple-900/30",
        iconColor: "text-purple-600 dark:text-purple-400",
        title: "5 năm kinh nghiệm",
        description: "Giáo viên có kinh nghiệm và tận tâm",
        order: 3,
      },
      {
        icon: "⏰",
        iconBg: "bg-orange-100 dark:bg-orange-900/30",
        iconColor: "text-orange-600 dark:text-orange-400",
        title: "Linh hoạt thời gian",
        description: "Lịch học phù hợp với công việc của bạn",
        order: 4,
      },
    ]
  })

  // ============= CTA Stats =============
  await prisma.ctaStat.createMany({
    data: [
      {
        value: 10000,
        suffix: "+",
        label: "Học viên",
        order: 1,
      },
      {
        value: 5,
        suffix: " năm",
        label: "Kinh nghiệm",
        order: 2,
      },
      {
        value: 98,
        suffix: "%",
        label: "Đậu HSK/HSKK",
        order: 3,
      },
    ]
  })

  // ============= Photo Albums =============
  const album1 = await prisma.album.create({
    data: {
      title: "Lớp học HSK 1 vui vẻ",
      description: "Ảnh lớp học HSK cấp độ 1",
      thumbnail: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=600&fit=crop",
      photoCount: 2,
      order: 1,
    },
  })

  await prisma.photo.createMany({
    data: [
      {
        albumId: album1.id,
        url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1920&h=1080&fit=crop",
        title: "Học viên trong lớp",
        description: "Các bạn học viên đang học tiếng Trung",
        order: 1,
      },
      {
        albumId: album1.id,
        url: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1920&h=1080&fit=crop",
        title: "Hoạt động nhóm",
        description: "Học viên thảo luận và làm bài tập nhóm",
        order: 2,
      },
    ]
  })

  const album2 = await prisma.album.create({
    data: {
      title: "Thực hành thư pháp",
      description: "Ảnh hoạt động văn hóa",
      thumbnail: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop",
      photoCount: 2,
      order: 2,
    },
  })

  await prisma.photo.createMany({
    data: [
      {
        albumId: album2.id,
        url: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=1920&h=1080&fit=crop",
        title: "Viết thư pháp",
        description: "Học viên thực hành viết chữ Hán",
        order: 1,
      },
      {
        albumId: album2.id,
        url: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=1920&h=1080&fit=crop",
        title: "Học từ vựng",
        description: "Luyện tập từ vựng và phát âm",
        order: 2,
      },
    ]
  })

  const album3 = await prisma.album.create({
    data: {
      title: "Hoạt động ngoại khóa",
      description: "Các hoạt động văn hóa và giao lưu",
      thumbnail: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=600&fit=crop",
      photoCount: 2,
      order: 3,
    },
  })

  await prisma.photo.createMany({
    data: [
      {
        albumId: album3.id,
        url: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1920&h=1080&fit=crop",
        title: "Thảo luận nhóm",
        description: "Học viên thảo luận dự án",
        order: 1,
      },
      {
        albumId: album3.id,
        url: "https://images.unsplash.com/photo-1531545514256-b1400bc00f31?w=1920&h=1080&fit=crop",
        title: "Học cùng giáo viên",
        description: "Giáo viên hướng dẫn học viên",
        order: 2,
      },
    ]
  })

  // ============= Reviews =============
  await prisma.review.createMany({
    data: [
      {
        studentName: "Chien Hoang",
        className: "HSK1",
        content: "Qua u la beautiful luon ~~~",
        rating: 5,
        isApproved: true,
        createdAt: new Date("2025-11-25T22:01:08"),
      },
      {
        studentName: "Chiên Hoàng",
        className: "Trọn đời",
        content: "Cô giáo siêu tuyệt vời, yêu cô giáo nhất trên đời <3",
        rating: 5,
        isApproved: true,
        createdAt: new Date("2025-09-28T23:41:59"),
      },
      {
        studentName: "Bảo Châu",
        className: "HSK1",
        content: "Cô giáo siêu giỏi",
        rating: 5,
        isApproved: true,
        createdAt: new Date("2025-09-27T23:47:18"),
      },
      {
        studentName: "Chien",
        className: "HSK",
        content: "Thật tuyệt vời",
        rating: 5,
        isApproved: true,
        createdAt: new Date("2025-09-26T21:22:52"),
      },
    ],
  })

  console.log("✅ Seed FULL completed with all home page data!")
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
